export const dashboardData = {
  periods: [
    { id: '7d', label: 'Aug 05 – Aug 12, 2026', shortLabel: 'Last 7 days' },
    { id: '30d', label: 'Jul 14 – Aug 12, 2026', shortLabel: 'Last 30 days' },
    { id: '90d', label: 'May 15 – Aug 12, 2026', shortLabel: 'Last 90 days' },
  ],
  navigation: [
    { id: 'overview', label: 'Overview', icon: 'grid', active: true },
    { id: 'merchants', label: 'Merchants', icon: 'store' },
    {
      id: 'reports',
      label: 'Reports',
      icon: 'chart',
      children: ['Performance', 'Transactions', 'Commission'],
    },
    {
      id: 'amazon',
      label: 'Amazon',
      icon: 'bag',
      children: ['Storefront', 'Orders', 'Products'],
    },
    { id: 'channels', label: 'Channels', icon: 'globe' },
    { id: 'payments', label: 'Payments', icon: 'wallet' },
    { id: 'accounts', label: 'Accounts', icon: 'users' },
    {
      id: 'tools',
      label: 'Tools',
      icon: 'tool',
      children: ['Link Builder', 'Product Feed', 'API Docs'],
    },
  ],
  metrics: [
    {
      id: 'clicks',
      label: 'Clicks',
      value: '48,620',
      change: '+12.8%',
      note: 'vs previous period',
      tone: 'blue',
      icon: 'cursor',
    },
    {
      id: 'sales',
      label: 'Sales',
      value: '1,284',
      change: '+8.4%',
      note: 'vs previous period',
      tone: 'cyan',
      icon: 'receipt',
    },
    {
      id: 'amount',
      label: 'Sale amount',
      value: '$186,420.80',
      change: '+15.2%',
      note: 'gross sales',
      tone: 'green',
      icon: 'dollar',
    },
    {
      id: 'commission',
      label: 'Approved commission',
      value: '$24,860.40',
      change: '+9.6%',
      note: 'ready to pay',
      tone: 'mint',
      icon: 'coins',
    },
    {
      id: 'cvr',
      label: 'CVR',
      value: '2.6%',
      change: '+0.3%',
      note: 'conversion rate',
      tone: 'sky',
      icon: 'trend',
    },
    {
      id: 'tasks',
      label: 'Tasks',
      value: '6',
      change: '2 due today',
      note: 'needs attention',
      tone: 'orange',
      icon: 'check',
    },
    {
      id: 'level',
      label: 'Level',
      value: 'D',
      change: 'Growth tier',
      note: 'next review in 18d',
      tone: 'purple',
      icon: 'award',
    },
  ],
  advertisers: [
    { id: 'appsumo', name: 'AppSumo', amount: '$6,845.20', percent: 100, trend: '+18.4%' },
    { id: 'shokz', name: 'Shokz', amount: '$5,126.80', percent: 75, trend: '+12.1%' },
    { id: 'eight-sleep', name: 'Eight Sleep', amount: '$4,382.10', percent: 64, trend: '+7.8%' },
    { id: 'briefcase', name: 'Briefcase', amount: '$3,614.60', percent: 53, trend: '+4.6%' },
    { id: 'todaysunny', name: 'TodaySunny', amount: '$2,906.40', percent: 42, trend: '+2.9%' },
  ],
  commission: {
    total: '$49.7K',
    approved: { label: 'Approved', value: '$24,860', percent: 50, tone: 'green' },
    pending: { label: 'Pending', value: '$6,420', percent: 13, tone: 'orange' },
    paid: { label: 'Total paid', value: '$18,440', percent: 37, tone: 'blue' },
  },
  merchantStatus: [
    { id: 'joined', label: 'Joined', value: 42, percent: 78, tone: 'green' },
    { id: 'pending', label: 'Pending', value: 8, percent: 15, tone: 'orange' },
    { id: 'rejected', label: 'Rejected', value: 3, percent: 7, tone: 'pink' },
  ],
  merchants: [
    {
      id: 'appsumo',
      displayId: '403359',
      name: 'AppSumo',
      mark: 'A',
      brandColor: '#7C3AED',
      logoBackground: '#F1EAFE',
      commission: '52.5%',
      commissionLabel: 'Revenue share',
      country: 'United States',
      countryCode: 'US',
      cookieDays: 30,
      domain: 'appsumo.com',
      category: 'Software & Internet',
      channel: 'Content / Blog',
      description: 'Curated software deals for entrepreneurs, creators and growing online businesses.',
      applied: false,
    },
    {
      id: 'briefcase',
      displayId: '403362',
      name: 'Briefcase',
      mark: 'B',
      brandColor: '#334155',
      logoBackground: '#EEF2F6',
      commission: '35%',
      commissionLabel: 'Per qualified sale',
      country: 'United Kingdom',
      countryCode: 'GB',
      cookieDays: 45,
      domain: 'briefcasehq.com',
      category: 'Business Services',
      channel: 'Content / Blog',
      description: 'Practical business resources and tools built for independent professionals.',
      applied: false,
    },
    {
      id: 'todaysunny',
      displayId: '403355',
      name: 'TodaySunny',
      mark: 'TS',
      brandColor: '#E69B13',
      logoBackground: '#FFF5D9',
      commission: '7.5%',
      commissionLabel: 'Commission rate',
      country: 'Canada',
      countryCode: 'CA',
      cookieDays: 14,
      domain: 'todaysunny.ca',
      category: 'Home & Lifestyle',
      channel: 'Deals / Coupon',
      description: 'Everyday lifestyle essentials selected for bright, comfortable living.',
      applied: false,
    },
    {
      id: 'shokz',
      displayId: '403371',
      name: 'Shokz',
      mark: 'S',
      brandColor: '#E84B2C',
      logoBackground: '#FFF0EC',
      commission: '12%',
      commissionLabel: 'Commission rate',
      country: 'United States',
      countryCode: 'US',
      cookieDays: 30,
      domain: 'shokz.com',
      category: 'Consumer Electronics',
      channel: 'Content / Social',
      description: 'Open-ear audio products designed for movement, focus and daily activity.',
      applied: false,
    },
    {
      id: 'eight-sleep',
      displayId: '403378',
      name: 'Eight Sleep',
      mark: '8',
      brandColor: '#172033',
      logoBackground: '#E9EDF4',
      commission: '$150',
      commissionLabel: 'Per approved order',
      country: 'United States',
      countryCode: 'US',
      cookieDays: 45,
      domain: 'eightsleep.com',
      category: 'Health & Wellness',
      channel: 'Premium Media',
      description: 'Smart sleep technology that helps people recover and perform at their best.',
      applied: false,
    },
    {
      id: 'closermate',
      displayId: '403384',
      name: 'CloserMate',
      mark: 'CM',
      brandColor: '#167B72',
      logoBackground: '#E4F6F2',
      commission: '28%',
      commissionLabel: 'Recurring revenue',
      country: 'Australia',
      countryCode: 'AU',
      cookieDays: 60,
      domain: 'closermate.io',
      category: 'Sales Software',
      channel: 'Content / Blog',
      description: 'A lightweight sales workspace for small teams that want clearer follow-up.',
      applied: false,
    },
  ],
};
