const sevenDaySnapshot = {
  metrics: [
    { id: 'clicks', label: 'Clicks', value: '48,620', change: '+12.8%', note: 'vs previous period', tone: 'blue', icon: 'cursor' },
    { id: 'orders', label: 'Orders', value: '1,284', change: '+8.4%', note: 'completed orders', tone: 'cyan', icon: 'receipt' },
    { id: 'gross-sales', label: 'Gross sales', value: '$186,420.80', change: '+15.2%', note: 'before adjustments', tone: 'green', icon: 'dollar' },
    { id: 'net-sales', label: 'Net sales', value: '$172,840.30', change: '+11.6%', note: 'after returns & voids', tone: 'mint', icon: 'trend' },
    { id: 'commission', label: 'Commission', value: '$24,860.40', change: '+9.6%', note: 'approved this period', tone: 'purple', icon: 'coins' },
    { id: 'conversion', label: 'Conversion', value: '2.6%', change: '+0.3%', note: 'click-to-order rate', tone: 'sky', icon: 'chart' },
    { id: 'total-payout', label: 'Total payout', value: '$31,280.40', change: '+7.9%', note: 'commission + fees', tone: 'orange', icon: 'wallet' },
  ],
  partnerPerformance: [
    { id: 'northstar', name: 'Northstar Media', type: 'Publisher', amount: '$6,845.20', percent: 100, trend: '+18.4%', orders: '214' },
    { id: 'dealroom', name: 'The Dealroom', type: 'Publisher', amount: '$5,126.80', percent: 75, trend: '+12.1%', orders: '186' },
    { id: 'shopper-edit', name: 'Shopper Edit', type: 'Influencer', amount: '$4,382.10', percent: 64, trend: '+7.8%', orders: '142' },
    { id: 'tech-forward', name: 'Tech Forward', type: 'Publisher', amount: '$3,614.60', percent: 53, trend: '+4.6%', orders: '118' },
    { id: 'daily-living', name: 'Daily Living', type: 'Influencer', amount: '$2,906.40', percent: 42, trend: '+2.9%', orders: '96' },
  ],
  commission: {
    total: '$49.7K',
    approved: { label: 'Approved', value: '$24,860', percent: 46, tone: 'green' },
    pending: { label: 'Pending approval', value: '$6,420', percent: 13, tone: 'orange' },
    paid: { label: 'Total paid', value: '$18,440', percent: 37, tone: 'blue' },
    voided: { label: 'Voided', value: '$1,280', percent: 4, tone: 'pink' },
  },
  partnerStatus: [
    { id: 'active', label: 'Active partners', value: 42, percent: 78, tone: 'green' },
    { id: 'applications', label: 'Applications pending', value: 12, percent: 22, tone: 'orange' },
    { id: 'invited', label: 'Invitations sent', value: 8, percent: 15, tone: 'blue' },
  ],
};

const thirtyDaySnapshot = {
  metrics: [
    { id: 'clicks', label: 'Clicks', value: '182,940', change: '+16.4%', note: 'vs previous period', tone: 'blue', icon: 'cursor' },
    { id: 'orders', label: 'Orders', value: '4,982', change: '+13.1%', note: 'completed orders', tone: 'cyan', icon: 'receipt' },
    { id: 'gross-sales', label: 'Gross sales', value: '$724,680.10', change: '+18.2%', note: 'before adjustments', tone: 'green', icon: 'dollar' },
    { id: 'net-sales', label: 'Net sales', value: '$681,240.70', change: '+14.4%', note: 'after returns & voids', tone: 'mint', icon: 'trend' },
    { id: 'commission', label: 'Commission', value: '$96,420.80', change: '+12.8%', note: 'approved this period', tone: 'purple', icon: 'coins' },
    { id: 'conversion', label: 'Conversion', value: '2.7%', change: '+0.4%', note: 'click-to-order rate', tone: 'sky', icon: 'chart' },
    { id: 'total-payout', label: 'Total payout', value: '$121,840.50', change: '+10.6%', note: 'commission + fees', tone: 'orange', icon: 'wallet' },
  ],
  partnerPerformance: [
    { id: 'northstar', name: 'Northstar Media', type: 'Publisher', amount: '$21,340.90', percent: 100, trend: '+20.6%', orders: '684' },
    { id: 'dealroom', name: 'The Dealroom', type: 'Publisher', amount: '$16,820.40', percent: 79, trend: '+14.8%', orders: '596' },
    { id: 'shopper-edit', name: 'Shopper Edit', type: 'Influencer', amount: '$13,280.10', percent: 62, trend: '+11.2%', orders: '452' },
    { id: 'tech-forward', name: 'Tech Forward', type: 'Publisher', amount: '$10,460.80', percent: 49, trend: '+8.6%', orders: '390' },
    { id: 'daily-living', name: 'Daily Living', type: 'Influencer', amount: '$8,620.30', percent: 40, trend: '+5.4%', orders: '316' },
  ],
  commission: {
    total: '$194.2K',
    approved: { label: 'Approved', value: '$96,420', percent: 46, tone: 'green' },
    pending: { label: 'Pending approval', value: '$28,180', percent: 15, tone: 'orange' },
    paid: { label: 'Total paid', value: '$69,600', percent: 35, tone: 'blue' },
    voided: { label: 'Voided', value: '$4,280', percent: 4, tone: 'pink' },
  },
  partnerStatus: [
    { id: 'active', label: 'Active partners', value: 48, percent: 71, tone: 'green' },
    { id: 'applications', label: 'Applications pending', value: 16, percent: 24, tone: 'orange' },
    { id: 'invited', label: 'Invitations sent', value: 11, percent: 16, tone: 'blue' },
  ],
};

const ninetyDaySnapshot = {
  metrics: [
    { id: 'clicks', label: 'Clicks', value: '526,840', change: '+21.2%', note: 'vs previous period', tone: 'blue', icon: 'cursor' },
    { id: 'orders', label: 'Orders', value: '14,620', change: '+17.6%', note: 'completed orders', tone: 'cyan', icon: 'receipt' },
    { id: 'gross-sales', label: 'Gross sales', value: '$2.18M', change: '+24.9%', note: 'before adjustments', tone: 'green', icon: 'dollar' },
    { id: 'net-sales', label: 'Net sales', value: '$2.05M', change: '+20.3%', note: 'after returns & voids', tone: 'mint', icon: 'trend' },
    { id: 'commission', label: 'Commission', value: '$286.4K', change: '+19.8%', note: 'approved this period', tone: 'purple', icon: 'coins' },
    { id: 'conversion', label: 'Conversion', value: '2.8%', change: '+0.5%', note: 'click-to-order rate', tone: 'sky', icon: 'chart' },
    { id: 'total-payout', label: 'Total payout', value: '$362.8K', change: '+18.1%', note: 'commission + fees', tone: 'orange', icon: 'wallet' },
  ],
  partnerPerformance: [
    { id: 'northstar', name: 'Northstar Media', type: 'Publisher', amount: '$64,280.30', percent: 100, trend: '+24.2%', orders: '2,140' },
    { id: 'dealroom', name: 'The Dealroom', type: 'Publisher', amount: '$51,620.40', percent: 80, trend: '+19.6%', orders: '1,864' },
    { id: 'shopper-edit', name: 'Shopper Edit', type: 'Influencer', amount: '$42,180.10', percent: 66, trend: '+16.2%', orders: '1,420' },
    { id: 'tech-forward', name: 'Tech Forward', type: 'Publisher', amount: '$32,460.80', percent: 50, trend: '+12.5%', orders: '1,080' },
    { id: 'daily-living', name: 'Daily Living', type: 'Influencer', amount: '$26,820.30', percent: 42, trend: '+9.6%', orders: '860' },
  ],
  commission: {
    total: '$582.8K',
    approved: { label: 'Approved', value: '$286,420', percent: 45, tone: 'green' },
    pending: { label: 'Pending approval', value: '$82,180', percent: 14, tone: 'orange' },
    paid: { label: 'Total paid', value: '$214,200', percent: 37, tone: 'blue' },
    voided: { label: 'Voided', value: '$11,280', percent: 4, tone: 'pink' },
  },
  partnerStatus: [
    { id: 'active', label: 'Active partners', value: 58, percent: 70, tone: 'green' },
    { id: 'applications', label: 'Applications pending', value: 21, percent: 25, tone: 'orange' },
    { id: 'invited', label: 'Invitations sent', value: 15, percent: 18, tone: 'blue' },
  ],
};

export const dashboardData = {
  workspace: {
    organization: 'YeahPromos',
    brand: 'Northstar Labs',
    store: 'US Store',
    role: 'Brand Admin',
    currency: 'USD',
    timezone: 'America/Los_Angeles',
  },
  periods: [
    { id: '7d', label: 'Aug 05 – Aug 12, 2026', shortLabel: 'Last 7 days', snapshot: sevenDaySnapshot },
    { id: '30d', label: 'Jul 14 – Aug 12, 2026', shortLabel: 'Last 30 days', snapshot: thirtyDaySnapshot },
    { id: '90d', label: 'May 15 – Aug 12, 2026', shortLabel: 'Last 90 days', snapshot: ninetyDaySnapshot },
  ],
  navigation: [
    { id: 'overview', label: 'Overview', icon: 'grid' },
    {
      id: 'recruitment',
      label: 'Recruitment & Partners',
      icon: 'users',
      children: [
        { id: 'discover-influencers', label: 'Discover influencers' },
        { id: 'discover-publishers', label: 'Discover publishers' },
        { id: 'my-partners', label: 'My partners' },
        { id: 'applications', label: 'Applications' },
        { id: 'invite-history', label: 'Invite history' },
      ],
    },
    {
      id: 'campaigns',
      label: 'Campaigns',
      icon: 'chart',
      children: [
        { id: 'all-campaigns', label: 'All campaigns' },
        { id: 'affiliate-programs', label: 'Affiliate programs' },
        { id: 'influencer-campaigns', label: 'Influencer campaigns' },
      ],
    },
    {
      id: 'products-assets',
      label: 'Products & Assets',
      icon: 'bag',
      children: [
        { id: 'product-feed', label: 'Product feed' },
        { id: 'coupons', label: 'Coupons' },
        { id: 'texts-emails', label: 'Texts & emails' },
        { id: 'banners-images', label: 'Banners & images' },
      ],
    },
    {
      id: 'commission-rules',
      label: 'Commission & Rules',
      icon: 'coins',
      children: [
        { id: 'commission-rules-list', label: 'Commission rules' },
        { id: 'attribution-rules', label: 'Attribution rules' },
      ],
    },
    {
      id: 'data-transactions',
      label: 'Data & Transactions',
      icon: 'trend',
      children: [
        { id: 'performance', label: 'Performance' },
        { id: 'performance-brand', label: 'Performance by brand' },
        { id: 'transactions', label: 'Transactions' },
        { id: 'amazon-brb', label: 'Amazon BRB' },
      ],
    },
    { id: 'finance', label: 'Finance', icon: 'wallet', children: [{ id: 'balance-payments', label: 'Balance & payments' }, { id: 'invoices', label: 'Invoices' }] },
    { id: 'messages', label: 'Messages & Notifications', icon: 'message' },
    {
      id: 'settings',
      label: 'Integrations & Settings',
      icon: 'settings',
      children: [
        { id: 'team-accounts', label: 'Team accounts' },
        { id: 'permissions', label: 'Permissions' },
        { id: 'brand-integration', label: 'Brand integration' },
        { id: 'api-credentials', label: 'API credentials' },
      ],
    },
  ],
  ...sevenDaySnapshot,
  lastUpdated: '4 min ago',
  actionItems: [
    {
      id: 'application-review',
      icon: 'users',
      tone: 'blue',
      eyebrow: 'Partner applications',
      title: '12 applications need review',
      description: 'New publisher channels are waiting for approval.',
      meta: '12 pending',
      action: 'Review applications',
      navigationId: 'applications',
    },
    {
      id: 'product-sync',
      icon: 'bag',
      tone: 'orange',
      eyebrow: 'Product feed sync',
      title: '3 products failed to sync',
      description: 'Review the ASIN errors before the next campaign launch.',
      meta: 'Sync failed',
      action: 'View errors',
      navigationId: 'product-feed',
    },
    {
      id: 'campaign-launch',
      icon: 'chart',
      tone: 'purple',
      eyebrow: 'Campaigns',
      title: 'Summer Sale starts in 5 days',
      description: 'Confirm offers, creatives and partner access before launch.',
      meta: 'Scheduled',
      action: 'Open campaign',
      navigationId: 'all-campaigns',
    },
    {
      id: 'transaction-approval',
      icon: 'receipt',
      tone: 'green',
      eyebrow: 'Transactions',
      title: '28 transactions are ready for approval',
      description: 'Approve or void transactions with a reason and audit trail.',
      meta: '28 pending',
      action: 'Review transactions',
      navigationId: 'transactions',
    },
  ],
  quickActions: [
    { id: 'invite-partner', icon: 'send', label: 'Invite partner', navigationId: 'invite-history' },
    { id: 'create-campaign', icon: 'chart', label: 'Create campaign', navigationId: 'all-campaigns' },
    { id: 'add-product', icon: 'bag', label: 'Add product', navigationId: 'product-feed' },
    { id: 'add-coupon', icon: 'tag', label: 'Add coupon', navigationId: 'coupons' },
    { id: 'export-report', icon: 'download', label: 'Export report', navigationId: 'performance' },
  ],
  partners: [
    {
      id: 'northstar',
      name: 'Northstar Media',
      type: 'Publisher',
      channel: 'Website / Content',
      status: 'Active',
      group: 'Premium publishers',
      audience: '1.2M monthly visits',
      commission: '$6,845.20',
    },
  ],
};


export const campaignPageData = {
  metrics: [
    { id: 'active-campaigns', label: 'Active campaigns', value: '18', change: '↑ 12.5%', note: 'vs Apr 28 – May 04', icon: 'users', sparkline: '0,26 12,18 25,31 37,16 48,25 60,10 71,17 84,12 96,6' },
    { id: 'click-throughs', label: 'Click-throughs', value: '282,401', change: '↑ 8.2%', note: 'vs Apr 28 – May 04', icon: 'cursor', sparkline: '0,25 12,18 25,31 36,17 48,24 60,7 72,14 84,4 96,10' },
    { id: 'campaign-orders', label: 'Orders', value: '6,521', change: '↑ 11.6%', note: 'vs Apr 28 – May 04', icon: 'receipt', sparkline: '0,23 12,16 24,29 36,19 47,26 60,9 70,15 84,5 96,9' },
    { id: 'campaign-sales', label: 'Sales', value: '$327,128.54', change: '↑ 9.7%', note: 'vs Apr 28 – May 04', icon: 'dollar', sparkline: '0,26 12,21 24,29 36,11 48,23 60,7 71,15 84,4 96,8' },
  ],
  campaigns: [
    {
      id: 'spring-collection-promo',
      name: 'Spring Collection Promo',
      code: 'CMP-2024-0001',
      type: 'Co-op',
      typeIcon: 'users',
      channel: 'Affiliate',
      channelIcon: 'users',
      status: 'Active',
      statusDetail: 'On track',
      stage: 'Execution',
      partners: '24',
      sales: '$62,845.22',
      orders: '32 orders',
      progress: 68,
      nextAction: 'Review assets',
      nextActionIcon: 'calendar',
      updated: 'May 16, 2025',
      updatedBy: 'Taylor Morgan',
    },
    {
      id: 'tech-essentials-launch',
      name: 'Tech Essentials Launch',
      code: 'CMP-2024-0002',
      type: 'MDF',
      typeIcon: 'coins',
      channel: 'Influencer',
      channelIcon: 'users',
      status: 'Pending',
      statusDetail: 'Awaiting approval',
      stage: 'Review',
      partners: '18',
      sales: '$44,318.19',
      orders: '892 orders',
      progress: 15,
      nextAction: 'Approve budget',
      nextActionIcon: 'users',
      updated: 'May 15, 2025',
      updatedBy: 'Alex Rivera',
    },
    {
      id: 'mothers-day-special',
      name: "Mother's Day Special",
      code: 'CMP-2024-0003',
      type: 'Event',
      typeIcon: 'calendar',
      channel: 'Affiliate',
      channelIcon: 'users',
      status: 'Completed',
      statusDetail: 'Completed',
      stage: 'Complete',
      partners: '36',
      sales: '$38,912.46',
      orders: '768 orders',
      progress: 100,
      nextAction: 'No action required',
      nextActionIcon: 'check',
      updated: 'May 10, 2025',
      updatedBy: 'Taylor Morgan',
    },
    {
      id: 'summer-sale-kickoff',
      name: 'Summer Sale Kickoff',
      code: 'CMP-2024-0004',
      type: 'Enablement',
      typeIcon: 'bag',
      channel: 'Publisher',
      channelIcon: 'send',
      status: 'Paused',
      statusDetail: 'Paused',
      stage: 'Execution',
      partners: '21',
      sales: '$28,433.71',
      orders: '543 orders',
      progress: 40,
      nextAction: 'Resume campaign',
      nextActionIcon: 'arrow',
      updated: 'May 9, 2025',
      updatedBy: 'Alex Rivera',
    },
    {
      id: 'back-to-school',
      name: 'Back to School',
      code: 'CMP-2024-0005',
      type: 'Co-op',
      typeIcon: 'users',
      channel: 'Affiliate',
      channelIcon: 'users',
      status: 'Draft',
      statusDetail: 'In planning',
      stage: 'Planning',
      partners: '12',
      sales: '$21,247.88',
      orders: '412 orders',
      progress: 30,
      nextAction: 'Add campaign assets',
      nextActionIcon: 'bag',
      updated: 'May 8, 2025',
      updatedBy: 'Jamie Lee',
    },
    {
      id: 'holiday-gift-guide',
      name: 'Holiday Gift Guide',
      code: 'CMP-2024-0006',
      type: 'MDF',
      typeIcon: 'coins',
      channel: 'Influencer',
      channelIcon: 'users',
      status: 'Closed',
      statusDetail: 'Completed',
      stage: 'Complete',
      partners: '15',
      sales: '$0',
      orders: '0 orders',
      progress: 100,
      nextAction: 'No action required',
      nextActionIcon: 'check',
      updated: 'May 6, 2025',
      updatedBy: 'Jamie Lee',
    },
    {
      id: 'brand-awareness-q2',
      name: 'Brand Awareness Q2',
      code: 'CMP-2024-0007',
      type: 'Event',
      typeIcon: 'calendar',
      channel: 'Publisher',
      channelIcon: 'send',
      status: 'Active',
      statusDetail: 'On track',
      stage: 'Execution',
      partners: '31',
      sales: '$33,614.93',
      orders: '678 orders',
      progress: 52,
      nextAction: 'Confirm attendance',
      nextActionIcon: 'calendar',
      updated: 'May 5, 2025',
      updatedBy: 'Taylor Morgan',
    },
    {
      id: 'flash-sale-weekend',
      name: 'Flash Sale Weekend',
      code: 'CMP-2024-0008',
      type: 'Enablement',
      typeIcon: 'bag',
      channel: 'Affiliate',
      channelIcon: 'users',
      status: 'Completed',
      statusDetail: 'Completed',
      stage: 'Complete',
      partners: '9',
      sales: '$15,362.15',
      orders: '312 orders',
      progress: 100,
      nextAction: 'No action required',
      nextActionIcon: 'check',
      updated: 'May 4, 2025',
      updatedBy: 'Alex Rivera',
    },
  ],
};
