const page = (id, title, parent, description, kind) => ({ id, title, parent, description, kind });

export const operationsPages = [
  page('performance', 'Performance', 'Data & Transactions', 'Track how your affiliate program is performing across key metrics.', 'performance'),
  page('performance-brand', 'Performance by brand', 'Data & Transactions', 'Compare performance across brands, stores, and partner channels.', 'performance-brand'),
  page('transactions', 'Transactions', 'Data & Transactions', 'Review, approve, and export the transactions generated by your affiliate program.', 'transactions'),
  page('amazon-brb', 'Amazon BRB', 'Data & Transactions', 'Monitor Amazon brand referral performance and campaign-level product activity.', 'amazon-brb'),
];

export const operationsPageIds = operationsPages.map(({ id }) => id);

const series = (label, values, display, color = 'brand') => ({
  label,
  display,
  color,
  points: values.map((value, index) => ({ label: ['May 05', 'May 06', 'May 07', 'May 08', 'May 09', 'May 10', 'May 11', 'May 12'][index], value })),
});

export const performanceSeries = {
  clicks: series('Clicks', [34200, 38500, 36200, 42900, 48800, 46200, 40400, 39900], 'count'),
  orders: series('Orders', [820, 940, 910, 1080, 1240, 1190, 1060, 1020], 'count'),
  commission: series('Commission', [21400, 24200, 22800, 27400, 31200, 29800, 26400, 25800], 'currency'),
  grossSales: series('Gross sales', [148000, 165000, 158000, 188000, 214000, 206000, 184000, 181000], 'currency'),
  netSales: series('Net sales', [138000, 155000, 149000, 178000, 203000, 196000, 175000, 172000], 'currency'),
  voids: series('Voids', [2800, 3200, 2900, 4100, 3600, 3300, 3800, 3100], 'currency'),
};

export const performanceMetricOptions = [
  ['clicks', 'Clicks'],
  ['orders', 'Orders'],
  ['commission', 'Commission'],
  ['grossSales', 'Gross sales'],
  ['netSales', 'Net sales'],
  ['voids', 'Voids'],
];

export const brandPerformanceRecords = [
  { id: 'northstar', brand: 'Northstar Labs', color: 'brand', clicks: '38,420', orders: '1,146', grossSales: '$86,420.20', commission: '$10,684.10', conversion: '2.98%' },
  { id: 'fieldhouse', brand: 'Fieldhouse Goods', color: 'ink', clicks: '26,810', orders: '842', grossSales: '$62,140.70', commission: '$7,286.50', conversion: '3.14%' },
  { id: 'canyon', brand: 'Canyon Home', color: 'success', clicks: '18,240', orders: '506', grossSales: '$42,680.40', commission: '$4,921.80', conversion: '2.77%' },
  { id: 'atlas', brand: 'Atlas Outdoor', color: 'warning', clicks: '12,604', orders: '318', grossSales: '$29,180.80', commission: '$3,414.90', conversion: '2.52%' },
];

export const transactionRecords = [
  { id: 'txn-1042', order: 'ORD-1042', partner: 'Alpha Media', brand: 'Northstar Labs', sku: 'NL-TRAIL-01', amount: '$428.00', commission: '$34.24', status: 'Pending', type: 'Sale', country: 'US', date: 'May 12, 2025 · 09:42' },
  { id: 'txn-1041', order: 'ORD-1041', partner: 'Future Hub', brand: 'Fieldhouse Goods', sku: 'FH-CANVAS-08', amount: '$286.50', commission: '$22.92', status: 'Paid', type: 'Sale', country: 'US', date: 'May 12, 2025 · 08:16' },
  { id: 'txn-1040', order: 'ORD-1040', partner: 'Gocertify', brand: 'Canyon Home', sku: 'CH-LAMP-02', amount: '$172.00', commission: '$13.76', status: 'Pending', type: 'Sale', country: 'CA', date: 'May 11, 2025 · 17:30' },
  { id: 'txn-1039', order: 'ORD-1039', partner: 'Creative Bytes', brand: 'Northstar Labs', sku: 'NL-JACKET-14', amount: '$640.00', commission: '$51.20', status: 'Paid', type: 'Sale', country: 'UK', date: 'May 11, 2025 · 14:02' },
  { id: 'txn-1038', order: 'ORD-1038', partner: 'Karma Collective', brand: 'Atlas Outdoor', sku: 'AO-PACK-03', amount: '$318.00', commission: '$25.44', status: 'Void', type: 'Return', country: 'US', date: 'May 11, 2025 · 11:46' },
  { id: 'txn-1037', order: 'ORD-1037', partner: 'The Dealroom', brand: 'Northstar Labs', sku: 'NL-TEE-06', amount: '$198.00', commission: '$15.84', status: 'Pending', type: 'Sale', country: 'AU', date: 'May 10, 2025 · 19:12' },
  { id: 'txn-1036', order: 'ORD-1036', partner: 'Shopper Edit', brand: 'Fieldhouse Goods', sku: 'FH-MUG-01', amount: '$74.00', commission: '$5.92', status: 'Paid', type: 'Sale', country: 'US', date: 'May 10, 2025 · 15:28' },
  { id: 'txn-1035', order: 'ORD-1035', partner: 'Daily Living', brand: 'Canyon Home', sku: 'CH-RUG-11', amount: '$520.00', commission: '$41.60', status: 'Pending', type: 'Sale', country: 'DE', date: 'May 10, 2025 · 10:08' },
];

export const amazonCampaignRecords = [
  { id: 'brb-summer', campaign: 'Summer Trail Essentials', status: 'Active', clicks: '18,420', detailViews: '12,840', carts: '4,320', purchases: '1,284', sales: '$68,420.40', date: 'May 01 – May 12' },
  { id: 'brb-home', campaign: 'Home Refresh Event', status: 'Active', clicks: '12,680', detailViews: '8,940', carts: '2,860', purchases: '842', sales: '$42,180.20', date: 'Apr 20 – May 12' },
  { id: 'brb-video', campaign: 'Video Creator Test', status: 'Draft', clicks: '4,210', detailViews: '2,806', carts: '684', purchases: '186', sales: '$9,620.80', date: 'May 08 – May 12' },
];

const stateKeyByPageId = {
  'performance-brand': 'performanceBrand',
  'amazon-brb': 'amazonBrb',
};

export const getOperationsStateKey = (pageId) => stateKeyByPageId[pageId] ?? pageId;

export function getOperationsPage(pageId) {
  return operationsPages.find((item) => item.id === pageId) ?? null;
}

export function createOperationsState() {
  return {
    performance: { query: '', filters: { cadence: 'Daily', partner: 'All partners' }, selectedId: null, tab: 'clicks' },
    performanceBrand: { query: '', filters: { cadence: 'Daily', brand: 'All brands' }, selectedId: null, tab: 'clicks' },
    transactions: { query: '', filters: { status: 'All statuses', country: 'All countries', type: 'All types' }, selectedId: null, tab: 'all' },
    amazonBrb: { query: '', filters: { cadence: 'Daily', date: 'May 01 – May 12, 2025' }, selectedId: 'brb-summer', tab: 'clicks' },
  };
}

export function filterOperationsRecords(records, { query = '', filters = {} } = {}) {
  const normalizedQuery = String(query ?? '').trim().toLowerCase();
  return records.filter((record) => {
    const searchable = Object.values(record).join(' ').toLowerCase();
    if (normalizedQuery && !searchable.includes(normalizedQuery)) return false;
    return Object.entries(filters).every(([key, expected]) => {
      if (!expected || /^all\b/i.test(String(expected))) return true;
      return String(record[key] ?? '').toLowerCase() === String(expected).toLowerCase();
    });
  });
}

function updatePageState(state, pageId, updater) {
  const key = getOperationsStateKey(pageId);
  if (!state[key]) return state;
  return { ...state, [key]: updater(state[key]) };
}

export function updateOperationsSearch(state, pageId, query) {
  return updatePageState(state, pageId, (pageState) => ({ ...pageState, query: String(query ?? '') }));
}

export function updateOperationsFilter(state, pageId, filterKey, value) {
  return updatePageState(state, pageId, (pageState) => ({ ...pageState, filters: { ...pageState.filters, [filterKey]: value } }));
}

export function selectOperationsRecord(state, pageId, recordId) {
  return updatePageState(state, pageId, (pageState) => ({ ...pageState, selectedId: recordId ?? null }));
}

export function selectOperationsTab(state, pageId, tab) {
  return updatePageState(state, pageId, (pageState) => ({ ...pageState, tab: tab ?? pageState.tab }));
}
