export const workflowCatalog = {
  'partner-invite': {
    id: 'partner-invite',
    ariaLabel: 'Partner invitation builder',
    eyebrow: 'PARTNER RECRUITMENT',
    title: 'Find, qualify, and invite',
    summary: 'Turn discovery filters, partner context, and a tailored message into one continuous flow.',
    steps: ['Discover', 'Profile', 'Invite'],
    capabilities: ['Audience filters', 'Channel profile', 'Message template'],
    source: 'Manual · Partner discovery / invitations',
  },
  'bulk-invite': {
    id: 'bulk-invite',
    ariaLabel: 'Bulk invitation builder',
    eyebrow: 'BULK RECRUITMENT',
    title: 'Invite a partner list at once',
    summary: 'Combine a reusable invitation link, manual recipients, and CSV import in a single batch composer.',
    steps: ['Recipients', 'Message', 'Review'],
    capabilities: ['Invite link', 'CSV upload', 'Batch message'],
    source: 'Manual · Bulk invite',
  },
  'application-review': {
    id: 'application-review',
    ariaLabel: 'Partner application review',
    eyebrow: 'APPLICATION DESK',
    title: 'Review with context',
    summary: 'See the applicant, channel footprint, audience fit, and approval controls without leaving the queue.',
    steps: ['Applicant', 'Evidence', 'Decision'],
    capabilities: ['Profile evidence', 'Auto approval', 'Approve / reject'],
    source: 'Manual · Partner applications',
  },
  'product-filter': {
    id: 'product-filter',
    ariaLabel: 'Amazon product filter builder',
    eyebrow: 'CATALOG CONTROL',
    title: 'Shape the partner product feed',
    summary: 'Apply storefront-level Amazon rules, validate ASINs, and retain an auditable upload history.',
    steps: ['Storefront', 'Rules', 'Validate'],
    capabilities: ['Whitelist rules', 'ASIN validation', 'Upload history'],
    source: 'Manual · Product feed / Amazon filters',
  },
  'commission-rule': {
    id: 'commission-rule',
    ariaLabel: 'Commission rule builder',
    eyebrow: 'INCENTIVE LOGIC',
    title: 'Build a precise commission rule',
    summary: 'Set the rate and active window, then combine product, partner, coupon, and customer conditions.',
    steps: ['Basics', 'Conditions', 'Publish'],
    capabilities: ['Rate window', 'Parent ASIN', 'Partner + coupon logic'],
    source: 'Manual · Commission rules',
  },
  'coupon-builder': {
    id: 'coupon-builder',
    ariaLabel: 'Coupon builder',
    eyebrow: 'OFFER MERCHANDISING',
    title: 'Package a coupon for partners',
    summary: 'Bring the visual, code, destination, restrictions, and availability together in one publishable asset.',
    steps: ['Creative', 'Offer', 'Publish'],
    capabilities: ['Image asset', 'Coupon code', 'Visibility rules'],
    source: 'Manual · Coupons',
  },
  'template-library': {
    id: 'template-library',
    ariaLabel: 'Message template library',
    eyebrow: 'COMMUNICATION SYSTEM',
    title: 'Write once, reuse with intent',
    summary: 'Organize reusable templates, preview the message, and move directly into a campaign-ready version.',
    steps: ['Library', 'Compose', 'Preview'],
    capabilities: ['Template folders', 'Rich message', 'Preview state'],
    source: 'Manual · Newsletter templates',
  },
  'report-builder': {
    id: 'report-builder',
    ariaLabel: 'Performance report builder',
    eyebrow: 'PERFORMANCE STUDIO',
    title: 'Build a decision-ready report',
    summary: 'Choose dimensions and metrics, inspect transaction detail, then save or export the working view.',
    steps: ['Measures', 'Arrange', 'Export'],
    capabilities: ['Metric dimensions', 'Saved report', 'CSV export'],
    source: 'Manual · Performance / transactions / BRB',
  },
  'payment-flow': {
    id: 'payment-flow',
    ariaLabel: 'Payment operations flow',
    eyebrow: 'FINANCE OPERATIONS',
    title: 'Fund, verify, and reconcile',
    summary: 'Keep balance, deposit method, payment status, and downloadable invoices in a traceable flow.',
    steps: ['Balance', 'Deposit', 'Reconcile'],
    capabilities: ['Balance check', 'Deposit method', 'Invoice detail'],
    source: 'Manual · Payments',
  },
  'permission-builder': {
    id: 'permission-builder',
    ariaLabel: 'Account permission builder',
    eyebrow: 'ACCESS DESIGN',
    title: 'Compose access by responsibility',
    summary: 'Assign brands, choose capabilities, and review the final permission set before inviting a teammate.',
    steps: ['Account', 'Permissions', 'Confirm'],
    capabilities: ['Brand scope', 'Permission tree', 'Allowed set'],
    source: 'Manual · Account permissions',
  },
};

const workflowByPage = {
  discover: 'partner-invite',
  'influencer-discovery': 'partner-invite',
  'publisher-discovery': 'partner-invite',
  'my-partners': 'partner-invite',
  'partner-groups': 'partner-invite',
  invitations: 'bulk-invite',
  applications: 'application-review',
  'product-feed': 'product-filter',
  'commission-rules': 'commission-rule',
  attribution: 'commission-rule',
  'ppc-rules': 'commission-rule',
  'link-parameters': 'commission-rule',
  coupons: 'coupon-builder',
  newsletters: 'template-library',
  templates: 'template-library',
  'text-assets': 'template-library',
  performance: 'report-builder',
  'brand-analysis': 'report-builder',
  transactions: 'report-builder',
  'transaction-inquiries': 'report-builder',
  'amazon-brb': 'report-builder',
  exports: 'report-builder',
  balance: 'payment-flow',
  payments: 'payment-flow',
  invoices: 'payment-flow',
  team: 'permission-builder',
};

export function workflowForPage(pageId) {
  return workflowByPage[pageId] ?? null;
}
